<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data=[
            ['codigo' => '010101', 'descripcion' => 'CHACHAPOYAS', 'provincia_id' => 1],
            ['codigo' => '010102', 'descripcion' => 'ASUNCION', 'provincia_id' => 1],
            ['codigo' => '010103', 'descripcion' => 'BALSAS', 'provincia_id' => 1],
            ['codigo' => '010104', 'descripcion' => 'CHETO', 'provincia_id' => 1],
            ['codigo' => '010105', 'descripcion' => 'CHILIQUIN', 'provincia_id' => 1],
            ['codigo' => '010106', 'descripcion' => 'CHUQUIBAMBA', 'provincia_id' => 1],
            ['codigo' => '010107', 'descripcion' => 'GRANADA', 'provincia_id' => 1],
            ['codigo' => '010108', 'descripcion' => 'HUANCAS', 'provincia_id' => 1],
            ['codigo' => '010109', 'descripcion' => 'LA JALCA', 'provincia_id' => 1],
            ['codigo' => '010110', 'descripcion' => 'LEIMEBAMBA', 'provincia_id' => 1],
            ['codigo' => '010111', 'descripcion' => 'LEVANTO', 'provincia_id' => 1],
            ['codigo' => '010112', 'descripcion' => 'MAGDALENA', 'provincia_id' => 1],
            ['codigo' => '010113', 'descripcion' => 'MARISCAL CASTILLA', 'provincia_id' => 1],
            ['codigo' => '010114', 'descripcion' => 'MOLINOPAMPA', 'provincia_id' => 1],
            ['codigo' => '010115', 'descripcion' => 'MONTEVIDEO', 'provincia_id' => 1],
            ['codigo' => '010116', 'descripcion' => 'OLLEROS', 'provincia_id' => 1],
            ['codigo' => '010117', 'descripcion' => 'QUINJALCA', 'provincia_id' => 1],
            ['codigo' => '010118', 'descripcion' => 'SAN FRANCISCO DE DAGUAS', 'provincia_id' => 1],
            ['codigo' => '010119', 'descripcion' => 'SAN ISIDRO DE MAINO', 'provincia_id' => 1],
            ['codigo' => '010120', 'descripcion' => 'SOLOCO', 'provincia_id' => 1],
            ['codigo' => '010121', 'descripcion' => 'SONCHE', 'provincia_id' => 1],
            ['codigo' => '010201', 'descripcion' => 'BAGUA', 'provincia_id' => 2],
            ['codigo' => '010202', 'descripcion' => 'ARAMANGO', 'provincia_id' => 2],
            ['codigo' => '010203', 'descripcion' => 'COPALLIN', 'provincia_id' => 2],
            ['codigo' => '010204', 'descripcion' => 'EL PARCO', 'provincia_id' => 2],
            ['codigo' => '010205', 'descripcion' => 'IMAZA', 'provincia_id' => 2],
            ['codigo' => '010206', 'descripcion' => 'LA PECA', 'provincia_id' => 2],
            ['codigo' => '010301', 'descripcion' => 'JUMBILLA', 'provincia_id' => 3],
            ['codigo' => '010302', 'descripcion' => 'CHISQUILLA', 'provincia_id' => 3],
            ['codigo' => '010303', 'descripcion' => 'CHURUJA', 'provincia_id' => 3],
            ['codigo' => '010304', 'descripcion' => 'COROSHA', 'provincia_id' => 3],
            ['codigo' => '010305', 'descripcion' => 'CUISPES', 'provincia_id' => 3],
            ['codigo' => '010306', 'descripcion' => 'FLORIDA', 'provincia_id' => 3],
            ['codigo' => '010307', 'descripcion' => 'JAZAN', 'provincia_id' => 3],
            ['codigo' => '010308', 'descripcion' => 'RECTA', 'provincia_id' => 3],
            ['codigo' => '010309', 'descripcion' => 'SAN CARLOS', 'provincia_id' => 3],
            ['codigo' => '010310', 'descripcion' => 'SHIPASBAMBA', 'provincia_id' => 3],
            ['codigo' => '010311', 'descripcion' => 'VALERA', 'provincia_id' => 3],
            ['codigo' => '010312', 'descripcion' => 'YAMBRASBAMBA', 'provincia_id' => 3],
            ['codigo' => '010401', 'descripcion' => 'NIEVA', 'provincia_id' => 4],
            ['codigo' => '010402', 'descripcion' => 'EL CENEPA', 'provincia_id' => 4],
            ['codigo' => '010403', 'descripcion' => 'RIO SANTIAGO', 'provincia_id' => 4],
            ['codigo' => '010501', 'descripcion' => 'LAMUD', 'provincia_id' => 5],
            ['codigo' => '010502', 'descripcion' => 'CAMPORREDONDO', 'provincia_id' => 5],
            ['codigo' => '010503', 'descripcion' => 'COCABAMBA', 'provincia_id' => 5],
            ['codigo' => '010504', 'descripcion' => 'COLCAMAR', 'provincia_id' => 5],
            ['codigo' => '010505', 'descripcion' => 'CONILA', 'provincia_id' => 5],
            ['codigo' => '010506', 'descripcion' => 'INGUILPATA', 'provincia_id' => 5],
            ['codigo' => '010507', 'descripcion' => 'LONGUITA', 'provincia_id' => 5],
            ['codigo' => '010508', 'descripcion' => 'LONYA CHICO', 'provincia_id' => 5],
            ['codigo' => '010509', 'descripcion' => 'LUYA', 'provincia_id' => 5],
            ['codigo' => '010510', 'descripcion' => 'LUYA VIEJO', 'provincia_id' => 5],
            ['codigo' => '010511', 'descripcion' => 'MARIA', 'provincia_id' => 5],
            ['codigo' => '010512', 'descripcion' => 'OCALLI', 'provincia_id' => 5],
            ['codigo' => '010513', 'descripcion' => 'OCUMAL', 'provincia_id' => 5],
            ['codigo' => '010514', 'descripcion' => 'PISUQUIA', 'provincia_id' => 5],
            ['codigo' => '010515', 'descripcion' => 'PROVIDENCIA', 'provincia_id' => 5],
            ['codigo' => '010516', 'descripcion' => 'SAN CRISTOBAL', 'provincia_id' => 5],
            ['codigo' => '010517', 'descripcion' => 'SAN FRANCISCO DEL YESO', 'provincia_id' => 5],
            ['codigo' => '010518', 'descripcion' => 'SAN JERONIMO', 'provincia_id' => 5],
            ['codigo' => '010519', 'descripcion' => 'SAN JUAN DE LOPECANCHA', 'provincia_id' => 5],
            ['codigo' => '010520', 'descripcion' => 'SANTA CATALINA', 'provincia_id' => 5],
            ['codigo' => '010521', 'descripcion' => 'SANTO TOMAS', 'provincia_id' => 5],
            ['codigo' => '010522', 'descripcion' => 'TINGO', 'provincia_id' => 5],
            ['codigo' => '010523', 'descripcion' => 'TRITA', 'provincia_id' => 5],
            ['codigo' => '010601', 'descripcion' => 'SAN NICOLAS', 'provincia_id' => 6],
            ['codigo' => '010602', 'descripcion' => 'CHIRIMOTO', 'provincia_id' => 6],
            ['codigo' => '010603', 'descripcion' => 'COCHAMAL', 'provincia_id' => 6],
            ['codigo' => '010604', 'descripcion' => 'HUAMBO', 'provincia_id' => 6],
            ['codigo' => '010605', 'descripcion' => 'LIMABAMBA', 'provincia_id' => 6],
            ['codigo' => '010606', 'descripcion' => 'LONGAR', 'provincia_id' => 6],
            ['codigo' => '010607', 'descripcion' => 'MARISCAL BENAVIDES', 'provincia_id' => 6],
            ['codigo' => '010608', 'descripcion' => 'MILPUC', 'provincia_id' => 6],
            ['codigo' => '010609', 'descripcion' => 'OMIA', 'provincia_id' => 6],
            ['codigo' => '010610', 'descripcion' => 'SANTA ROSA', 'provincia_id' => 6],
            ['codigo' => '010611', 'descripcion' => 'TOTORA', 'provincia_id' => 6],
            ['codigo' => '010612', 'descripcion' => 'VISTA ALEGRE', 'provincia_id' => 6],
            ['codigo' => '010701', 'descripcion' => 'BAGUA GRANDE', 'provincia_id' => 7],
            ['codigo' => '010702', 'descripcion' => 'CAJARURO', 'provincia_id' => 7],
            ['codigo' => '010703', 'descripcion' => 'CUMBA', 'provincia_id' => 7],
            ['codigo' => '010704', 'descripcion' => 'EL MILAGRO', 'provincia_id' => 7],
            ['codigo' => '010705', 'descripcion' => 'JAMALCA', 'provincia_id' => 7],
            ['codigo' => '010706', 'descripcion' => 'LONYA GRANDE', 'provincia_id' => 7],
            ['codigo' => '010707', 'descripcion' => 'YAMON', 'provincia_id' => 7],
            ['codigo' => '020101', 'descripcion' => 'HUARAZ', 'provincia_id' => 8],
            ['codigo' => '020102', 'descripcion' => 'COCHABAMBA', 'provincia_id' => 8],
            ['codigo' => '020103', 'descripcion' => 'COLCABAMBA', 'provincia_id' => 8],
            ['codigo' => '020104', 'descripcion' => 'HUANCHAY', 'provincia_id' => 8],
            ['codigo' => '020105', 'descripcion' => 'INDEPENDENCIA', 'provincia_id' => 8],
            ['codigo' => '020106', 'descripcion' => 'JANGAS', 'provincia_id' => 8],
            ['codigo' => '020107', 'descripcion' => 'LA LIBERTAD', 'provincia_id' => 8],
            ['codigo' => '020108', 'descripcion' => 'OLLEROS', 'provincia_id' => 8],
            ['codigo' => '020109', 'descripcion' => 'PAMPAS', 'provincia_id' => 8],
            ['codigo' => '020110', 'descripcion' => 'PARIACOTO', 'provincia_id' => 8],
            ['codigo' => '020111', 'descripcion' => 'PIRA', 'provincia_id' => 8],
            ['codigo' => '020112', 'descripcion' => 'TARICA', 'provincia_id' => 8],
            ['codigo' => '020201', 'descripcion' => 'AIJA', 'provincia_id' => 9],
            ['codigo' => '020202', 'descripcion' => 'CORIS', 'provincia_id' => 9],
            ['codigo' => '020203', 'descripcion' => 'HUACLLAN', 'provincia_id' => 9],
            ['codigo' => '020204', 'descripcion' => 'LA MERCED', 'provincia_id' => 9],
            ['codigo' => '020205', 'descripcion' => 'SUCCHA', 'provincia_id' => 9],
            ['codigo' => '020301', 'descripcion' => 'LLAMELLIN', 'provincia_id' => 10],
            ['codigo' => '020302', 'descripcion' => 'ACZO', 'provincia_id' => 10],
            ['codigo' => '020303', 'descripcion' => 'CHACCHO', 'provincia_id' => 10],
            ['codigo' => '020304', 'descripcion' => 'CHINGAS', 'provincia_id' => 10],
            ['codigo' => '020305', 'descripcion' => 'MIRGAS', 'provincia_id' => 10],
            ['codigo' => '020306', 'descripcion' => 'SAN JUAN DE RONTOY', 'provincia_id' => 10],
            ['codigo' => '020401', 'descripcion' => 'CHACAS', 'provincia_id' => 11],
            ['codigo' => '020402', 'descripcion' => 'ACOCHACA', 'provincia_id' => 11],
            ['codigo' => '020501', 'descripcion' => 'CHIQUIAN', 'provincia_id' => 12],
            ['codigo' => '020502', 'descripcion' => 'ABELARDO PARDO LEZAMETA', 'provincia_id' => 12],
            ['codigo' => '020503', 'descripcion' => 'ANTONIO RAYMONDI', 'provincia_id' => 12],
            ['codigo' => '020504', 'descripcion' => 'AQUIA', 'provincia_id' => 12],
            ['codigo' => '020505', 'descripcion' => 'CAJACAY', 'provincia_id' => 12],
            ['codigo' => '020506', 'descripcion' => 'CANIS', 'provincia_id' => 12],
            ['codigo' => '020507', 'descripcion' => 'COLQUIOC', 'provincia_id' => 12],
            ['codigo' => '020508', 'descripcion' => 'HUALLANCA', 'provincia_id' => 12],
            ['codigo' => '020509', 'descripcion' => 'HUASTA', 'provincia_id' => 12],
            ['codigo' => '020510', 'descripcion' => 'HUAYLLACAYAN', 'provincia_id' => 12],
            ['codigo' => '020511', 'descripcion' => 'LA PRIMAVERA', 'provincia_id' => 12],
            ['codigo' => '020512', 'descripcion' => 'MANGAS', 'provincia_id' => 12],
            ['codigo' => '020513', 'descripcion' => 'PACLLON', 'provincia_id' => 12],
            ['codigo' => '020514', 'descripcion' => 'SAN MIGUEL DE CORPANQUI', 'provincia_id' => 12],
            ['codigo' => '020515', 'descripcion' => 'TICLLOS', 'provincia_id' => 12],
            ['codigo' => '020601', 'descripcion' => 'CARHUAZ', 'provincia_id' => 13],
            ['codigo' => '020602', 'descripcion' => 'ACOPAMPA', 'provincia_id' => 13],
            ['codigo' => '020603', 'descripcion' => 'AMASHCA', 'provincia_id' => 13],
            ['codigo' => '020604', 'descripcion' => 'ANTA', 'provincia_id' => 13],
            ['codigo' => '020605', 'descripcion' => 'ATAQUERO', 'provincia_id' => 13],
            ['codigo' => '020606', 'descripcion' => 'MARCARA', 'provincia_id' => 13],
            ['codigo' => '020607', 'descripcion' => 'PARIAHUANCA', 'provincia_id' => 13],
            ['codigo' => '020608', 'descripcion' => 'SAN MIGUEL DE ACO', 'provincia_id' => 13],
            ['codigo' => '020609', 'descripcion' => 'SHILLA', 'provincia_id' => 13],
            ['codigo' => '020610', 'descripcion' => 'TINCO', 'provincia_id' => 13],
            ['codigo' => '020611', 'descripcion' => 'YUNGAR', 'provincia_id' => 13],
            ['codigo' => '020701', 'descripcion' => 'SAN LUIS', 'provincia_id' => 14],
            ['codigo' => '020702', 'descripcion' => 'SAN NICOLAS', 'provincia_id' => 14],
            ['codigo' => '020703', 'descripcion' => 'YAUYA', 'provincia_id' => 14],
            ['codigo' => '020801', 'descripcion' => 'CASMA', 'provincia_id' => 15],
            ['codigo' => '020802', 'descripcion' => 'BUENA VISTA ALTA', 'provincia_id' => 15],
            ['codigo' => '020803', 'descripcion' => 'COMANDANTE NOEL', 'provincia_id' => 15],
            ['codigo' => '020804', 'descripcion' => 'YAUTAN', 'provincia_id' => 15],
            ['codigo' => '020901', 'descripcion' => 'CORONGO', 'provincia_id' => 16],
            ['codigo' => '020902', 'descripcion' => 'ACO', 'provincia_id' => 16],
            ['codigo' => '020903', 'descripcion' => 'BAMBAS', 'provincia_id' => 16],
            ['codigo' => '020904', 'descripcion' => 'CUSCA', 'provincia_id' => 16],
            ['codigo' => '020905', 'descripcion' => 'LA PAMPA', 'provincia_id' => 16],
            ['codigo' => '020906', 'descripcion' => 'YANAC', 'provincia_id' => 16],
            ['codigo' => '020907', 'descripcion' => 'YUPAN', 'provincia_id' => 16],
            ['codigo' => '021001', 'descripcion' => 'HUARI', 'provincia_id' => 17],
            ['codigo' => '021002', 'descripcion' => 'ANRA', 'provincia_id' => 17],
            ['codigo' => '021003', 'descripcion' => 'CAJAY', 'provincia_id' => 17],
            ['codigo' => '021004', 'descripcion' => 'CHAVIN DE HUANTAR', 'provincia_id' => 17],
            ['codigo' => '021005', 'descripcion' => 'HUACACHI', 'provincia_id' => 17],
            ['codigo' => '021006', 'descripcion' => 'HUACCHIS', 'provincia_id' => 17],
            ['codigo' => '021007', 'descripcion' => 'HUACHIS', 'provincia_id' => 17],
            ['codigo' => '021008', 'descripcion' => 'HUANTAR', 'provincia_id' => 17],
            ['codigo' => '021009', 'descripcion' => 'MASIN', 'provincia_id' => 17],
            ['codigo' => '021010', 'descripcion' => 'PAUCAS', 'provincia_id' => 17],
            ['codigo' => '021011', 'descripcion' => 'PONTO', 'provincia_id' => 17],
            ['codigo' => '021012', 'descripcion' => 'RAHUAPAMPA', 'provincia_id' => 17],
            ['codigo' => '021013', 'descripcion' => 'RAPAYAN', 'provincia_id' => 17],
            ['codigo' => '021014', 'descripcion' => 'SAN MARCOS', 'provincia_id' => 17],
            ['codigo' => '021015', 'descripcion' => 'SAN PEDRO DE CHANA', 'provincia_id' => 17],
            ['codigo' => '021016', 'descripcion' => 'UCO', 'provincia_id' => 17],
            ['codigo' => '021101', 'descripcion' => 'HUARMEY', 'provincia_id' => 18],
    ['codigo' => '021102', 'descripcion' => 'COCHAPETI', 'provincia_id' => 18],
    ['codigo' => '021103', 'descripcion' => 'CULEBRAS', 'provincia_id' => 18],
    ['codigo' => '021104', 'descripcion' => 'HUAYAN', 'provincia_id' => 18],
    ['codigo' => '021105', 'descripcion' => 'MALVAS', 'provincia_id' => 18],
    ['codigo' => '021201', 'descripcion' => 'CARAZ', 'provincia_id' => 19],
    ['codigo' => '021202', 'descripcion' => 'HUALLANCA', 'provincia_id' => 19],
    ['codigo' => '021203', 'descripcion' => 'HUATA', 'provincia_id' => 19],
    ['codigo' => '021204', 'descripcion' => 'HUAYLAS', 'provincia_id' => 19],
    ['codigo' => '021205', 'descripcion' => 'MATO', 'provincia_id' => 19],
    ['codigo' => '021206', 'descripcion' => 'PAMPAROMAS', 'provincia_id' => 19],
    ['codigo' => '021207', 'descripcion' => 'PUEBLO LIBRE', 'provincia_id' => 19],
    ['codigo' => '021208', 'descripcion' => 'SANTA CRUZ', 'provincia_id' => 19],
    ['codigo' => '021209', 'descripcion' => 'SANTO TORIBIO', 'provincia_id' => 19],
    ['codigo' => '021210', 'descripcion' => 'YURACMARCA', 'provincia_id' => 19],
    ['codigo' => '021301', 'descripcion' => 'PISCOBAMBA', 'provincia_id' => 20],
    ['codigo' => '021302', 'descripcion' => 'CASCA', 'provincia_id' => 20],
    ['codigo' => '021303', 'descripcion' => 'ELEAZAR GUZMAN BARRON', 'provincia_id' => 20],
    ['codigo' => '021304', 'descripcion' => 'FIDEL OLIVAS ESCUDERO', 'provincia_id' => 20],
    ['codigo' => '021305', 'descripcion' => 'LLAMA', 'provincia_id' => 20],
    ['codigo' => '021306', 'descripcion' => 'LLUMPA', 'provincia_id' => 20],
    ['codigo' => '021307', 'descripcion' => 'LUCMA', 'provincia_id' => 20],
    ['codigo' => '021308', 'descripcion' => 'MUSGA', 'provincia_id' => 20],
    ['codigo' => '021401', 'descripcion' => 'OCROS', 'provincia_id' => 21],
    ['codigo' => '021402', 'descripcion' => 'ACAS', 'provincia_id' => 21],
    ['codigo' => '021403', 'descripcion' => 'CAJAMARQUILLA', 'provincia_id' => 21],
    ['codigo' => '021404', 'descripcion' => 'CARHUAPAMPA', 'provincia_id' => 21],
    ['codigo' => '021405', 'descripcion' => 'COCHAS', 'provincia_id' => 21],
    ['codigo' => '021406', 'descripcion' => 'CONGAS', 'provincia_id' => 21],
    ['codigo' => '021407', 'descripcion' => 'LLIPA', 'provincia_id' => 21],
    ['codigo' => '021408', 'descripcion' => 'SAN CRISTOBAL DE RAJAN', 'provincia_id' => 21],
    ['codigo' => '021409', 'descripcion' => 'SAN PEDRO', 'provincia_id' => 21],
    ['codigo' => '021410', 'descripcion' => 'SANTIAGO DE CHILCAS', 'provincia_id' => 21],
    ['codigo' => '021501', 'descripcion' => 'CABANA', 'provincia_id' => 22],
    ['codigo' => '021502', 'descripcion' => 'BOLOGNESI', 'provincia_id' => 22],
    ['codigo' => '021503', 'descripcion' => 'CONCHUCOS', 'provincia_id' => 22],
    ['codigo' => '021504', 'descripcion' => 'HUACASCHUQUE', 'provincia_id' => 22],
    ['codigo' => '021505', 'descripcion' => 'HUANDOVAL', 'provincia_id' => 22],
    ['codigo' => '021506', 'descripcion' => 'LACABAMBA', 'provincia_id' => 22],
    ['codigo' => '021507', 'descripcion' => 'LLAPO', 'provincia_id' => 22],
    ['codigo' => '021508', 'descripcion' => 'PALLASCA', 'provincia_id' => 22],
    ['codigo' => '021509', 'descripcion' => 'PAMPAS', 'provincia_id' => 22],
    ['codigo' => '021510', 'descripcion' => 'SANTA ROSA', 'provincia_id' => 22],
    ['codigo' => '021511', 'descripcion' => 'TAUCA', 'provincia_id' => 22],
    ['codigo' => '021601', 'descripcion' => 'POMABAMBA', 'provincia_id' => 23],
    ['codigo' => '021602', 'descripcion' => 'HUAYLLAN', 'provincia_id' => 23],
    ['codigo' => '021603', 'descripcion' => 'PAROBAMBA', 'provincia_id' => 23],
    ['codigo' => '021604', 'descripcion' => 'QUINUABAMBA', 'provincia_id' => 23],
    ['codigo' => '021701', 'descripcion' => 'RECUAY', 'provincia_id' => 24],
    ['codigo' => '021702', 'descripcion' => 'CATAC', 'provincia_id' => 24],
    ['codigo' => '021703', 'descripcion' => 'COTAPARACO', 'provincia_id' => 24],
    ['codigo' => '021704', 'descripcion' => 'HUAYLLAPAMPA', 'provincia_id' => 24],
    ['codigo' => '021705', 'descripcion' => 'LLACLLIN', 'provincia_id' => 24],
    ['codigo' => '021706', 'descripcion' => 'MARCA', 'provincia_id' => 24],
    ['codigo' => '021707', 'descripcion' => 'PAMPAS CHICO', 'provincia_id' => 24],
    ['codigo' => '021708', 'descripcion' => 'PARARIN', 'provincia_id' => 24],
    ['codigo' => '021709', 'descripcion' => 'TAPACOCHA', 'provincia_id' => 24],
    ['codigo' => '021710', 'descripcion' => 'TICAPAMPA', 'provincia_id' => 24],
    ['codigo' => '021801', 'descripcion' => 'CHIMBOTE', 'provincia_id' => 25],
    ['codigo' => '021802', 'descripcion' => 'CACERES DEL PERU', 'provincia_id' => 25],
    ['codigo' => '021803', 'descripcion' => 'COISHCO', 'provincia_id' => 25],
    ['codigo' => '021804', 'descripcion' => 'MACATE', 'provincia_id' => 25],
    ['codigo' => '021805', 'descripcion' => 'MORO', 'provincia_id' => 25],
    ['codigo' => '021806', 'descripcion' => 'NEPEÑA', 'provincia_id' => 25],
    ['codigo' => '021807', 'descripcion' => 'SAMANCO', 'provincia_id' => 25],
    ['codigo' => '021808', 'descripcion' => 'SANTA', 'provincia_id' => 25],
    ['codigo' => '021809', 'descripcion' => 'NUEVO CHIMBOTE', 'provincia_id' => 25],
    ['codigo' => '021901', 'descripcion' => 'SIHUAS', 'provincia_id' => 26],
    ['codigo' => '021902', 'descripcion' => 'ACOBAMBA', 'provincia_id' => 26],
    ['codigo' => '021903', 'descripcion' => 'ALFONSO UGARTE', 'provincia_id' => 26],
    ['codigo' => '021904', 'descripcion' => 'CASHAPAMPA', 'provincia_id' => 26],
    ['codigo' => '021905', 'descripcion' => 'CHINGALPO', 'provincia_id' => 26],
    ['codigo' => '021906', 'descripcion' => 'HUAYLLABAMBA', 'provincia_id' => 26],
    ['codigo' => '021907', 'descripcion' => 'QUICHES', 'provincia_id' => 26],
    ['codigo' => '021908', 'descripcion' => 'RAGASH', 'provincia_id' => 26],
    ['codigo' => '021909', 'descripcion' => 'SAN JUAN', 'provincia_id' => 26],
    ['codigo' => '021910', 'descripcion' => 'SICSIBAMBA', 'provincia_id' => 26],
    ['codigo' => '022001', 'descripcion' => 'YUNGAY', 'provincia_id' => 27],
    ['codigo' => '022002', 'descripcion' => 'CASCAPARA', 'provincia_id' => 27],
    ['codigo' => '022003', 'descripcion' => 'MANCOS', 'provincia_id' => 27],
    ['codigo' => '022004', 'descripcion' => 'MATACOTO', 'provincia_id' => 27],
    ['codigo' => '022005', 'descripcion' => 'QUILLO', 'provincia_id' => 27],
    ['codigo' => '022006', 'descripcion' => 'RANRAHIRCA', 'provincia_id' => 27],
    ['codigo' => '022007', 'descripcion' => 'SHUPLUY', 'provincia_id' => 27],
    ['codigo' => '022008', 'descripcion' => 'YANAMA', 'provincia_id' => 27],
    ['codigo' => '030101', 'descripcion' => 'ABANCAY', 'provincia_id' => 28],
    ['codigo' => '030102', 'descripcion' => 'CHACOCHE', 'provincia_id' => 28],
    ['codigo' => '030103', 'descripcion' => 'CIRCA', 'provincia_id' => 28],
    ['codigo' => '030104', 'descripcion' => 'CURAHUASI', 'provincia_id' => 28],
    ['codigo' => '030105', 'descripcion' => 'HUANIPACA', 'provincia_id' => 28],
    ['codigo' => '030106', 'descripcion' => 'LAMBRAMA', 'provincia_id' => 28],
    ['codigo' => '030107', 'descripcion' => 'PICHIRHUA', 'provincia_id' => 28],
    ['codigo' => '030108', 'descripcion' => 'SAN PEDRO DE CACHORA', 'provincia_id' => 28],
    ['codigo' => '030109', 'descripcion' => 'TAMBURCO', 'provincia_id' => 28],
    ['codigo' => '030201', 'descripcion' => 'ANDAHUAYLAS', 'provincia_id' => 29],
    ['codigo' => '030202', 'descripcion' => 'ANDARAPA', 'provincia_id' => 29],
    ['codigo' => '030203', 'descripcion' => 'CHIARA', 'provincia_id' => 29],
    ['codigo' => '030204', 'descripcion' => 'HUANCARAMA', 'provincia_id' => 29],
    ['codigo' => '030205', 'descripcion' => 'HUANCARAY', 'provincia_id' => 29],
    ['codigo' => '030206', 'descripcion' => 'HUAYANA', 'provincia_id' => 29],
    ['codigo' => '030207', 'descripcion' => 'KISHUARA', 'provincia_id' => 29],
    ['codigo' => '030208', 'descripcion' => 'PACOBAMBA', 'provincia_id' => 29],
    ['codigo' => '030209', 'descripcion' => 'PACUCHA', 'provincia_id' => 29],
    ['codigo' => '030210', 'descripcion' => 'PAMPACHIRI', 'provincia_id' => 29],
    ['codigo' => '030211', 'descripcion' => 'POMACOCHA', 'provincia_id' => 29],
    ['codigo' => '030212', 'descripcion' => 'SAN ANTONIO DE CACHI', 'provincia_id' => 29],
    ['codigo' => '030213', 'descripcion' => 'SAN JERONIMO', 'provincia_id' => 29],
    ['codigo' => '030214', 'descripcion' => 'SAN MIGUEL DE CHACCRAMPA', 'provincia_id' => 29],
    ['codigo' => '030215', 'descripcion' => 'SANTA MARIA DE CHICMO', 'provincia_id' => 29],
    ['codigo' => '030216', 'descripcion' => 'TALAVERA', 'provincia_id' => 29],
    ['codigo' => '030217', 'descripcion' => 'TUMAY HUARACA', 'provincia_id' => 29],
    ['codigo' => '030218', 'descripcion' => 'TURPO', 'provincia_id' => 29],
    ['codigo' => '030219', 'descripcion' => 'KAQUIABAMBA', 'provincia_id' => 29],
    ['codigo' => '030301', 'descripcion' => 'ANTABAMBA', 'provincia_id' => 30],
    ['codigo' => '030302', 'descripcion' => 'EL ORO', 'provincia_id' => 30],
    ['codigo' => '030303', 'descripcion' => 'HUAQUIRCA', 'provincia_id' => 30],
    ['codigo' => '030304', 'descripcion' => 'JUAN ESPINOZA MEDRANO', 'provincia_id' => 30],
    ['codigo' => '030305', 'descripcion' => 'OROPESA', 'provincia_id' => 30],
    ['codigo' => '030306', 'descripcion' => 'PACHACONAS', 'provincia_id' => 30],
    ['codigo' => '030307', 'descripcion' => 'SABAINO', 'provincia_id' => 30],
    ['codigo' => '030401', 'descripcion' => 'CHALHUANCA', 'provincia_id' => 31],
    ['codigo' => '030402', 'descripcion' => 'CAPAYA', 'provincia_id' => 31],
    ['codigo' => '030403', 'descripcion' => 'CARAYBAMBA', 'provincia_id' => 31],
    ['codigo' => '030404', 'descripcion' => 'CHAPIMARCA', 'provincia_id' => 31],
    ['codigo' => '030405', 'descripcion' => 'COLCABAMBA', 'provincia_id' => 31],
    ['codigo' => '030406', 'descripcion' => 'COTARUSE', 'provincia_id' => 31],
    ['codigo' => '030407', 'descripcion' => 'HUAYLLO', 'provincia_id' => 31],
    ['codigo' => '030408', 'descripcion' => 'JUSTO APU SAHUARAURA', 'provincia_id' => 31],
    ['codigo' => '030409', 'descripcion' => 'LUCRE', 'provincia_id' => 31],
    ['codigo' => '030410', 'descripcion' => 'POCOHUANCA', 'provincia_id' => 31],
    ['codigo' => '030411', 'descripcion' => 'SAN JUAN DE CHACÑA', 'provincia_id' => 31],
    ['codigo' => '030412', 'descripcion' => 'SAÑAYCA', 'provincia_id' => 31],
    ['codigo' => '030413', 'descripcion' => 'SORAYA', 'provincia_id' => 31],
    ['codigo' => '030414', 'descripcion' => 'TAPAIRIHUA', 'provincia_id' => 31],
    ['codigo' => '030415', 'descripcion' => 'TINTAY', 'provincia_id' => 31],
    ['codigo' => '030416', 'descripcion' => 'TORAY', 'provincia_id' => 31],
    ['codigo' => '030417', 'descripcion' => 'YANACA', 'provincia_id' => 31],

    // Provincia 32 (Cotabambas)
    ['codigo' => '030501', 'descripcion' => 'TAMBOBAMBA', 'provincia_id' => 32],
    ['codigo' => '030502', 'descripcion' => 'COTABAMBAS', 'provincia_id' => 32],
    ['codigo' => '030503', 'descripcion' => 'COYLLURQUI', 'provincia_id' => 32],
    ['codigo' => '030504', 'descripcion' => 'HAQUIRA', 'provincia_id' => 32],
    ['codigo' => '030505', 'descripcion' => 'MARA', 'provincia_id' => 32],
    ['codigo' => '030506', 'descripcion' => 'CHALLHUAHUACHO', 'provincia_id' => 32],

    // Provincia 33 (Chincheros)
    ['codigo' => '030601', 'descripcion' => 'CHINCHEROS', 'provincia_id' => 33],
    ['codigo' => '030602', 'descripcion' => 'ANCO-HUALLO', 'provincia_id' => 33],
    ['codigo' => '030603', 'descripcion' => 'COCHARCAS', 'provincia_id' => 33],
    ['codigo' => '030604', 'descripcion' => 'HUACCANA', 'provincia_id' => 33],
    ['codigo' => '030605', 'descripcion' => 'OCOBAMBA', 'provincia_id' => 33],
    ['codigo' => '030606', 'descripcion' => 'ONGOY', 'provincia_id' => 33],
    ['codigo' => '030607', 'descripcion' => 'URANMARCA', 'provincia_id' => 33],
    ['codigo' => '030608', 'descripcion' => 'RANRACANCHA', 'provincia_id' => 33],

    // Provincia 34 (Grau)
    ['codigo' => '030701', 'descripcion' => 'CHUQUIBAMBILLA', 'provincia_id' => 34],
    ['codigo' => '030702', 'descripcion' => 'CURPAHUASI', 'provincia_id' => 34],
    ['codigo' => '030703', 'descripcion' => 'GAMARRA', 'provincia_id' => 34],
    ['codigo' => '030704', 'descripcion' => 'HUAYLLATI', 'provincia_id' => 34],
    ['codigo' => '030705', 'descripcion' => 'MAMARA', 'provincia_id' => 34],
    ['codigo' => '030706', 'descripcion' => 'MICAELA BASTIDAS', 'provincia_id' => 34],
    ['codigo' => '030707', 'descripcion' => 'PATAYPAMPA', 'provincia_id' => 34],
    ['codigo' => '030708', 'descripcion' => 'PROGRESO', 'provincia_id' => 34],
    ['codigo' => '030709', 'descripcion' => 'SAN ANTONIO', 'provincia_id' => 34],
    ['codigo' => '030710', 'descripcion' => 'SANTA ROSA', 'provincia_id' => 34],
    ['codigo' => '030711', 'descripcion' => 'TURPAY', 'provincia_id' => 34],
    ['codigo' => '030712', 'descripcion' => 'VILCABAMBA', 'provincia_id' => 34],
    ['codigo' => '030713', 'descripcion' => 'VIRUNDO', 'provincia_id' => 34],
    ['codigo' => '030714', 'descripcion' => 'CURASCO', 'provincia_id' => 34],
    ['codigo' => '040101', 'descripcion' => 'AREQUIPA', 'provincia_id' => 41],
    ['codigo' => '040102', 'descripcion' => 'ALTO SELVA ALEGRE', 'provincia_id' => 41],
    ['codigo' => '040103', 'descripcion' => 'CAYMA', 'provincia_id' => 41],
    ['codigo' => '040104', 'descripcion' => 'CERRO COLORADO', 'provincia_id' => 41],
    ['codigo' => '040105', 'descripcion' => 'CHARACATO', 'provincia_id' => 41],
    ['codigo' => '040106', 'descripcion' => 'CHIGUATA', 'provincia_id' => 41],
    ['codigo' => '040107', 'descripcion' => 'JACOBO HUNTER', 'provincia_id' => 41],
    ['codigo' => '040108', 'descripcion' => 'LA JOYA', 'provincia_id' => 41],
    ['codigo' => '040109', 'descripcion' => 'MARIANO MELGAR', 'provincia_id' => 41],
    ['codigo' => '040110', 'descripcion' => 'MIRAFLORES', 'provincia_id' => 41],
    ['codigo' => '040111', 'descripcion' => 'MOLLEBAYA', 'provincia_id' => 41],
    ['codigo' => '040112', 'descripcion' => 'PAUCARPATA', 'provincia_id' => 41],
    ['codigo' => '040113', 'descripcion' => 'POCSI', 'provincia_id' => 41],
    ['codigo' => '040114', 'descripcion' => 'POLOBAYA', 'provincia_id' => 41],
    ['codigo' => '040115', 'descripcion' => 'QUEQUEÑA', 'provincia_id' => 41],
    ['codigo' => '040116', 'descripcion' => 'SABANDIA', 'provincia_id' => 41],
    ['codigo' => '040117', 'descripcion' => 'SACHACA', 'provincia_id' => 41],
    ['codigo' => '040118', 'descripcion' => 'SAN JUAN DE SIGUAS /1', 'provincia_id' => 41],
    ['codigo' => '040119', 'descripcion' => 'SAN JUAN DE TARUCANI', 'provincia_id' => 41],
    ['codigo' => '040120', 'descripcion' => 'SANTA ISABEL DE SIGUAS', 'provincia_id' => 41],
    ['codigo' => '040121', 'descripcion' => 'SANTA RITA DE SIGUAS', 'provincia_id' => 41],
    ['codigo' => '040122', 'descripcion' => 'SOCABAYA', 'provincia_id' => 41],
    ['codigo' => '040123', 'descripcion' => 'TIABAYA', 'provincia_id' => 41],
    ['codigo' => '040124', 'descripcion' => 'UCHUMAYO', 'provincia_id' => 41],
    ['codigo' => '040125', 'descripcion' => 'VITOR', 'provincia_id' => 41],
    ['codigo' => '040126', 'descripcion' => 'YANAHUARA', 'provincia_id' => 41],
    ['codigo' => '040127', 'descripcion' => 'YARABAMBA', 'provincia_id' => 41],
    ['codigo' => '040128', 'descripcion' => 'YURA', 'provincia_id' => 41],
    ['codigo' => '040129', 'descripcion' => 'JOSE LUIS BUSTAMANTE Y RIVERO', 'provincia_id' => 41],

    // Provincia 42 (Camaná)
    ['codigo' => '040201', 'descripcion' => 'CAMANA', 'provincia_id' => 42],
    ['codigo' => '040202', 'descripcion' => 'JOSE MARIA QUIMPER', 'provincia_id' => 42],
    ['codigo' => '040203', 'descripcion' => 'MARIANO NICOLAS VALCARCEL', 'provincia_id' => 42],
    ['codigo' => '040204', 'descripcion' => 'MARISCAL CACERES', 'provincia_id' => 42],
    ['codigo' => '040205', 'descripcion' => 'NICOLAS DE PIEROLA', 'provincia_id' => 42],
    ['codigo' => '040206', 'descripcion' => 'OCOÑA', 'provincia_id' => 42],
    ['codigo' => '040207', 'descripcion' => 'QUILCA', 'provincia_id' => 42],
    ['codigo' => '040208', 'descripcion' => 'SAMUEL PASTOR', 'provincia_id' => 42],

    // Provincia 43 (Caravelí)
    ['codigo' => '040301', 'descripcion' => 'CARAVELI', 'provincia_id' => 43],
    ['codigo' => '040302', 'descripcion' => 'ACARI', 'provincia_id' => 43],
    ['codigo' => '040303', 'descripcion' => 'ATICO', 'provincia_id' => 43],
    ['codigo' => '040304', 'descripcion' => 'ATIQUIPA', 'provincia_id' => 43],
    ['codigo' => '040305', 'descripcion' => 'BELLA UNION', 'provincia_id' => 43],
    ['codigo' => '040306', 'descripcion' => 'CAHUACHO', 'provincia_id' => 43],
    ['codigo' => '040307', 'descripcion' => 'CHALA', 'provincia_id' => 43],
    ['codigo' => '040308', 'descripcion' => 'CHAPARRA', 'provincia_id' => 43],
    ['codigo' => '040309', 'descripcion' => 'HUANUHUANU', 'provincia_id' => 43],
    ['codigo' => '040310', 'descripcion' => 'JAQUI', 'provincia_id' => 43],
    ['codigo' => '040311', 'descripcion' => 'LOMAS', 'provincia_id' => 43],
    ['codigo' => '040312', 'descripcion' => 'QUICACHA', 'provincia_id' => 43],
    ['codigo' => '040313', 'descripcion' => 'YAUCA', 'provincia_id' => 43],

    // Provincia 44 (Castilla)
    ['codigo' => '040401', 'descripcion' => 'APLAO', 'provincia_id' => 44],
    ['codigo' => '040402', 'descripcion' => 'ANDAGUA', 'provincia_id' => 44],
    ['codigo' => '040403', 'descripcion' => 'AYO', 'provincia_id' => 44],
    ['codigo' => '040404', 'descripcion' => 'CHACHAS', 'provincia_id' => 44],
    ['codigo' => '040405', 'descripcion' => 'CHILCAYMARCA', 'provincia_id' => 44],
    ['codigo' => '040406', 'descripcion' => 'CHOCO', 'provincia_id' => 44],
    ['codigo' => '040407', 'descripcion' => 'HUANCARQUI', 'provincia_id' => 44],
    ['codigo' => '040408', 'descripcion' => 'MACHAGUAY', 'provincia_id' => 44],
    ['codigo' => '040409', 'descripcion' => 'ORCOPAMPA', 'provincia_id' => 44],
    ['codigo' => '040410', 'descripcion' => 'PAMPACOLCA', 'provincia_id' => 44],
    ['codigo' => '040411', 'descripcion' => 'TIPAN', 'provincia_id' => 44],
    ['codigo' => '040412', 'descripcion' => 'UÑON', 'provincia_id' => 44],
    ['codigo' => '040413', 'descripcion' => 'URACA', 'provincia_id' => 44],
    ['codigo' => '040414', 'descripcion' => 'VIRACO', 'provincia_id' => 44],

    // Provincia 45 (Caylloma)
    ['codigo' => '040501', 'descripcion' => 'CHIVAY', 'provincia_id' => 45],
    ['codigo' => '040502', 'descripcion' => 'ACHOMA', 'provincia_id' => 45],
    ['codigo' => '040503', 'descripcion' => 'CABANACONDE', 'provincia_id' => 45],
    ['codigo' => '040504', 'descripcion' => 'CALLALLI', 'provincia_id' => 45],
    ['codigo' => '040505', 'descripcion' => 'CAYLLOMA', 'provincia_id' => 45],
    ['codigo' => '040506', 'descripcion' => 'COPORAQUE', 'provincia_id' => 45],
    ['codigo' => '040507', 'descripcion' => 'HUAMBO', 'provincia_id' => 45],
    ['codigo' => '040508', 'descripcion' => 'HUANCA', 'provincia_id' => 45],
    ['codigo' => '040509', 'descripcion' => 'ICHUPAMPA', 'provincia_id' => 45],
    ['codigo' => '040510', 'descripcion' => 'LARI', 'provincia_id' => 45],
    ['codigo' => '040511', 'descripcion' => 'LLUTA', 'provincia_id' => 45],
    ['codigo' => '040512', 'descripcion' => 'MACA', 'provincia_id' => 45],
    ['codigo' => '040513', 'descripcion' => 'MADRIGAL', 'provincia_id' => 45],
    ['codigo' => '040514', 'descripcion' => 'SAN ANTONIO DE CHUCA', 'provincia_id' => 45],
    ['codigo' => '040515', 'descripcion' => 'SIBAYO', 'provincia_id' => 45],
    ['codigo' => '040516', 'descripcion' => 'TAPAY', 'provincia_id' => 45],
    ['codigo' => '040517', 'descripcion' => 'TISCO', 'provincia_id' => 45],
    ['codigo' => '040518', 'descripcion' => 'TUTI', 'provincia_id' => 45],
// Provincia 45 (Caylloma)
['codigo' => '040519', 'descripcion' => 'YANQUE', 'provincia_id' => 45],
['codigo' => '040520', 'descripcion' => 'MAJES', 'provincia_id' => 45],

// Provincia 46 (Condesuyos)
['codigo' => '040601', 'descripcion' => 'CHUQUIBAMBA', 'provincia_id' => 46],
['codigo' => '040602', 'descripcion' => 'ANDARAY', 'provincia_id' => 46],
['codigo' => '040603', 'descripcion' => 'CAYARANI', 'provincia_id' => 46],
['codigo' => '040604', 'descripcion' => 'CHICHAS', 'provincia_id' => 46],
['codigo' => '040605', 'descripcion' => 'IRAY', 'provincia_id' => 46],
['codigo' => '040606', 'descripcion' => 'RIO GRANDE', 'provincia_id' => 46],
['codigo' => '040607', 'descripcion' => 'SALAMANCA', 'provincia_id' => 46],
['codigo' => '040608', 'descripcion' => 'YANAQUIHUA', 'provincia_id' => 46],

// Provincia 47 (Islay)
['codigo' => '040701', 'descripcion' => 'MOLLENDO', 'provincia_id' => 47],
['codigo' => '040702', 'descripcion' => 'COCACHACRA', 'provincia_id' => 47],
['codigo' => '040703', 'descripcion' => 'DEAN VALDIVIA', 'provincia_id' => 47],
['codigo' => '040704', 'descripcion' => 'ISLAY', 'provincia_id' => 47],
['codigo' => '040705', 'descripcion' => 'MEJIA', 'provincia_id' => 47],
['codigo' => '040706', 'descripcion' => 'PUNTA DE BOMBON', 'provincia_id' => 47],

// Provincia 48 (La Unión)
['codigo' => '040801', 'descripcion' => 'COTAHUASI', 'provincia_id' => 48],
['codigo' => '040802', 'descripcion' => 'ALCA', 'provincia_id' => 48],
['codigo' => '040803', 'descripcion' => 'CHARCANA', 'provincia_id' => 48],
['codigo' => '040804', 'descripcion' => 'HUAYNACOTAS', 'provincia_id' => 48],
['codigo' => '040805', 'descripcion' => 'PAMPAMARCA', 'provincia_id' => 48],
['codigo' => '040806', 'descripcion' => 'PUYCA', 'provincia_id' => 48],
['codigo' => '040807', 'descripcion' => 'QUECHUALLA', 'provincia_id' => 48],
['codigo' => '040808', 'descripcion' => 'SAYLA', 'provincia_id' => 48],
['codigo' => '040809', 'descripcion' => 'TAURIA', 'provincia_id' => 48],
['codigo' => '040810', 'descripcion' => 'TOMEPAMPA', 'provincia_id' => 48],
['codigo' => '040811', 'descripcion' => 'TORO', 'provincia_id' => 48],

// Provincia 49 (Ayacucho)
['codigo' => '050101', 'descripcion' => 'AYACUCHO', 'provincia_id' => 49],
['codigo' => '050102', 'descripcion' => 'ACOCRO', 'provincia_id' => 49],
['codigo' => '050103', 'descripcion' => 'ACOS VINCHOS', 'provincia_id' => 49],
['codigo' => '050104', 'descripcion' => 'CARMEN ALTO', 'provincia_id' => 49],
['codigo' => '050105', 'descripcion' => 'CHIARA', 'provincia_id' => 49],
['codigo' => '050106', 'descripcion' => 'OCROS', 'provincia_id' => 49],
['codigo' => '050107', 'descripcion' => 'PACAYCASA', 'provincia_id' => 49],
['codigo' => '050108', 'descripcion' => 'QUINUA', 'provincia_id' => 49],
['codigo' => '050109', 'descripcion' => 'SAN JOSE DE TICLLAS', 'provincia_id' => 49],
['codigo' => '050110', 'descripcion' => 'SAN JUAN BAUTISTA', 'provincia_id' => 49],
['codigo' => '050111', 'descripcion' => 'SANTIAGO DE PISCHA', 'provincia_id' => 49],
['codigo' => '050112', 'descripcion' => 'SOCOS', 'provincia_id' => 49],
['codigo' => '050113', 'descripcion' => 'TAMBILLO', 'provincia_id' => 49],
['codigo' => '050114', 'descripcion' => 'VINCHOS', 'provincia_id' => 49],
['codigo' => '050115', 'descripcion' => 'JESUS NAZARENO', 'provincia_id' => 49],

// Provincia 50 (Cangallo)
['codigo' => '050201', 'descripcion' => 'CANGALLO', 'provincia_id' => 50],
['codigo' => '050202', 'descripcion' => 'CHUSCHI', 'provincia_id' => 50],
['codigo' => '050203', 'descripcion' => 'LOS MOROCHUCOS', 'provincia_id' => 50],
['codigo' => '050204', 'descripcion' => 'MARIA PARADO DE BELLIDO', 'provincia_id' => 50],
['codigo' => '050205', 'descripcion' => 'PARAS', 'provincia_id' => 50],
['codigo' => '050206', 'descripcion' => 'TOTOS', 'provincia_id' => 50],
// Provincia 51 (Sancos)
['codigo' => '050301', 'descripcion' => 'SANCOS', 'provincia_id' => 51],
['codigo' => '050302', 'descripcion' => 'CARAPO', 'provincia_id' => 51],
['codigo' => '050303', 'descripcion' => 'SACSAMARCA', 'provincia_id' => 51],
['codigo' => '050304', 'descripcion' => 'SANTIAGO DE LUCANAMARCA', 'provincia_id' => 51],

// Provincia 52 (Huanta)
['codigo' => '050401', 'descripcion' => 'HUANTA', 'provincia_id' => 52],
['codigo' => '050402', 'descripcion' => 'AYAHUANCO', 'provincia_id' => 52],
['codigo' => '050403', 'descripcion' => 'HUAMANGUILLA', 'provincia_id' => 52],
['codigo' => '050404', 'descripcion' => 'IGUAIN', 'provincia_id' => 52],
['codigo' => '050405', 'descripcion' => 'LURICOCHA', 'provincia_id' => 52],
['codigo' => '050406', 'descripcion' => 'SANTILLANA', 'provincia_id' => 52],
['codigo' => '050407', 'descripcion' => 'SIVIA', 'provincia_id' => 52],
['codigo' => '050408', 'descripcion' => 'LLOCHEGUA', 'provincia_id' => 52],

// Provincia 53 (La Mar)
['codigo' => '050501', 'descripcion' => 'SAN MIGUEL', 'provincia_id' => 53],
['codigo' => '050502', 'descripcion' => 'ANCO', 'provincia_id' => 53],
['codigo' => '050503', 'descripcion' => 'AYNA', 'provincia_id' => 53],
['codigo' => '050504', 'descripcion' => 'CHILCAS', 'provincia_id' => 53],
['codigo' => '050505', 'descripcion' => 'CHUNGUI', 'provincia_id' => 53],
['codigo' => '050506', 'descripcion' => 'LUIS CARRANZA', 'provincia_id' => 53],
['codigo' => '050507', 'descripcion' => 'SANTA ROSA', 'provincia_id' => 53],
['codigo' => '050508', 'descripcion' => 'TAMBO', 'provincia_id' => 53],

// Provincia 54 (Lucanas)
['codigo' => '050601', 'descripcion' => 'PUQUIO', 'provincia_id' => 54],
['codigo' => '050602', 'descripcion' => 'AUCARA', 'provincia_id' => 54],
['codigo' => '050603', 'descripcion' => 'CABANA', 'provincia_id' => 54],
['codigo' => '050604', 'descripcion' => 'CARMEN SALCEDO', 'provincia_id' => 54],
['codigo' => '050605', 'descripcion' => 'CHAVIÑA', 'provincia_id' => 54],
['codigo' => '050606', 'descripcion' => 'CHIPAO', 'provincia_id' => 54],
['codigo' => '050607', 'descripcion' => 'HUAC-HUAS', 'provincia_id' => 54],
['codigo' => '050608', 'descripcion' => 'LARAMATE', 'provincia_id' => 54],
['codigo' => '050609', 'descripcion' => 'LEONCIO PRADO', 'provincia_id' => 54],
['codigo' => '050610', 'descripcion' => 'LLAUTA', 'provincia_id' => 54],
['codigo' => '050611', 'descripcion' => 'LUCANAS', 'provincia_id' => 54],
['codigo' => '050612', 'descripcion' => 'OCAÑA', 'provincia_id' => 54],
['codigo' => '050613', 'descripcion' => 'OTOCA', 'provincia_id' => 54],
['codigo' => '050614', 'descripcion' => 'SAISA', 'provincia_id' => 54],
['codigo' => '050615', 'descripcion' => 'SAN CRISTOBAL', 'provincia_id' => 54],
['codigo' => '050616', 'descripcion' => 'SAN JUAN', 'provincia_id' => 54],
['codigo' => '050617', 'descripcion' => 'SAN PEDRO', 'provincia_id' => 54],
['codigo' => '050618', 'descripcion' => 'SAN PEDRO DE PALCO', 'provincia_id' => 54],
['codigo' => '050619', 'descripcion' => 'SANCOS', 'provincia_id' => 54],
['codigo' => '050620', 'descripcion' => 'SANTA ANA DE HUAYCAHUACHO', 'provincia_id' => 54],
['codigo' => '050621', 'descripcion' => 'SANTA LUCIA', 'provincia_id' => 54],

// Provincia 55 (Parinacochas)
['codigo' => '050701', 'descripcion' => 'CORACORA', 'provincia_id' => 55],
['codigo' => '050702', 'descripcion' => 'CHUMPI', 'provincia_id' => 55],
// Provincia 55 (Parinacochas)
['codigo' => '050701', 'descripcion' => 'CORACORA', 'provincia_id' => 55],
['codigo' => '050702', 'descripcion' => 'CHUMPI', 'provincia_id' => 55],
['codigo' => '050703', 'descripcion' => 'CORONEL CASTAÑEDA', 'provincia_id' => 55],
['codigo' => '050704', 'descripcion' => 'PACAPAUSA', 'provincia_id' => 55],
['codigo' => '050705', 'descripcion' => 'PULLO', 'provincia_id' => 55],
['codigo' => '050706', 'descripcion' => 'PUYUSCA', 'provincia_id' => 55],
['codigo' => '050707', 'descripcion' => 'SAN FRANCISCO DE RAVACAYCO', 'provincia_id' => 55],
['codigo' => '050708', 'descripcion' => 'UPAHUACHO', 'provincia_id' => 55],

// Provincia 56 (Páucar del Sara Sara)
['codigo' => '050801', 'descripcion' => 'PAUSA', 'provincia_id' => 56],
['codigo' => '050802', 'descripcion' => 'COLTA', 'provincia_id' => 56],
['codigo' => '050803', 'descripcion' => 'CORCULLA', 'provincia_id' => 56],
['codigo' => '050804', 'descripcion' => 'LAMPA', 'provincia_id' => 56],
['codigo' => '050805', 'descripcion' => 'MARCABAMBA', 'provincia_id' => 56],
['codigo' => '050806', 'descripcion' => 'OYOLO', 'provincia_id' => 56],
['codigo' => '050807', 'descripcion' => 'PARARCA', 'provincia_id' => 56],
['codigo' => '050808', 'descripcion' => 'SAN JAVIER DE ALPABAMBA', 'provincia_id' => 56],
['codigo' => '050809', 'descripcion' => 'SAN JOSE DE USHUA', 'provincia_id' => 56],
['codigo' => '050810', 'descripcion' => 'SARA SARA', 'provincia_id' => 56],

// Provincia 57 (Sucre)
['codigo' => '050901', 'descripcion' => 'QUEROBAMBA', 'provincia_id' => 57],
['codigo' => '050902', 'descripcion' => 'BELEN', 'provincia_id' => 57],
['codigo' => '050903', 'descripcion' => 'CHALCOS', 'provincia_id' => 57],
['codigo' => '050904', 'descripcion' => 'CHILCAYOC', 'provincia_id' => 57],
['codigo' => '050905', 'descripcion' => 'HUACAÑA', 'provincia_id' => 57],
['codigo' => '050906', 'descripcion' => 'MORCOLLA', 'provincia_id' => 57],
['codigo' => '050907', 'descripcion' => 'PAICO', 'provincia_id' => 57],
['codigo' => '050908', 'descripcion' => 'SAN PEDRO DE LARCAY', 'provincia_id' => 57],
['codigo' => '050909', 'descripcion' => 'SAN SALVADOR DE QUIJE', 'provincia_id' => 57],
['codigo' => '050910', 'descripcion' => 'SANTIAGO DE PAUCARAY', 'provincia_id' => 57],
['codigo' => '050911', 'descripcion' => 'SORAS', 'provincia_id' => 57],

// Provincia 58 (Víctor Fajardo)
['codigo' => '051001', 'descripcion' => 'HUANCAPI', 'provincia_id' => 58],
['codigo' => '051002', 'descripcion' => 'ALCAMENCA', 'provincia_id' => 58],
['codigo' => '051003', 'descripcion' => 'APONGO', 'provincia_id' => 58],
['codigo' => '051004', 'descripcion' => 'ASQUIPATA', 'provincia_id' => 58],
['codigo' => '051005', 'descripcion' => 'CANARIA', 'provincia_id' => 58],
['codigo' => '051006', 'descripcion' => 'CAYARA', 'provincia_id' => 58],
['codigo' => '051007', 'descripcion' => 'COLCA', 'provincia_id' => 58],
['codigo' => '051008', 'descripcion' => 'HUAMANQUIQUIA', 'provincia_id' => 58],
['codigo' => '051009', 'descripcion' => 'HUANCARAYLLA', 'provincia_id' => 58],

    


];
    }
}
