<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [

            ['codigo' => '0101', 'descripcion' => 'CHACHAPOYAS', 'departamento_id' => 1],
            ['codigo' => '0102', 'descripcion' => 'BAGUA'], 'departamento_id' => 1,
            ['codigo' => '0103', 'descripcion' => 'BONGARA', 'departamento_id' => 1],
            ['codigo' => '0104', 'descripcion' => 'CONDORCANQUI', 'departamento_id' => 1],
            ['codigo' => '0105', 'descripcion' => 'LUYA', 'departamento_id' => 1],
            ['codigo' => '0106', 'descripcion' => 'RODRIGUEZ DE MENDOZA', 'departamento_id' => 1],
            ['codigo' => '0107', 'descripcion' => 'UTCUBAMBA', 'departamento_id' => 1],
            ['codigo' => '0201', 'descripcion' => 'HUARAZ', 'departamento_id' => 2],
            ['codigo' => '0202', 'descripcion' => 'AIJA', 'departamento_id' => 2],
            ['codigo' => '0203', 'descripcion' => 'ANTONIO RAYMONDI', 'departamento_id' => 2],
            ['codigo' => '0204', 'descripcion' => 'ASUNCION', 'departamento_id' => 2],
            ['codigo' => '0205', 'descripcion' => 'BOLOGNESI', 'departamento_id' => 2],
            ['codigo' => '0206', 'descripcion' => 'CARHUAZ', 'departamento_id' => 2],
            ['codigo' => '0207', 'descripcion' => 'CARLOS FERMIN FITZCARRALD', 'departamento_id' => 2],
            ['codigo' => '0208', 'descripcion' => 'Casma', 'departamento_id' => 2],
            ['codigo' => '0209', 'descripcion' => 'CORONGO', 'departamento_id' => 2],
            ['codigo' => '0210', 'descripcion' => 'HUARI', 'departamento_id' => 2],
            ['codigo' => '0211', 'descripcion' => 'HUARMEY', 'departamento_id' => 2],
            ['codigo' => '0212', 'descripcion' => 'HUAYLAS', 'departamento_id' => 2],
            ['codigo' => '0213', 'descripcion' => 'MARISCAL LUZURIAGA', 'departamento_id' => 2],
            ['codigo' => '0214', 'descripcion' => 'OCROS', 'departamento_id' => 2],
            ['codigo' => '0215', 'descripcion' => 'PALLASCA', 'departamento_id' => 2],
            ['codigo' => '0216', 'descripcion' => 'POMABAMBA', 'departamento_id' => 2],
            ['codigo' => '0217', 'descripcion' => 'RECUAY', 'departamento_id' => 2],
            ['codigo' => '0218', 'descripcion' => 'SANTA', 'departamento_id' => 2],
            ['codigo' => '0219', 'descripcion' => 'SIHUAS', 'departamento_id' => 2],
            ['codigo' => '0220', 'descripcion' => 'YUNGAY', 'departamento_id' => 2],
            ['codigo' => '0301', 'descripcion' => 'ABANCAY', 'departamento_id' => 3],
            ['codigo' => '0302', 'descripcion' => 'ANDAHUAYLAS', 'departamento_id' => 3],
            ['codigo' => '0303', 'descripcion' => 'ANTABAMBA', 'departamento_id' => 3],
            ['codigo' => '0304', 'descripcion' => 'AYMARAES', 'departamento_id' => 3],
            ['codigo' => '0305', 'descripcion' => 'COTABAMBAS', 'departamento_id' => 3],
            ['codigo' => '0306', 'descripcion' => 'CHINCHEROS', 'departamento_id' => 3],
            ['codigo' => '0307', 'descripcion' => 'GRAU', 'departamento_id' => 3],
            ['codigo' => '0401', 'descripcion' => 'AREQUIPA', 'departamento_id' => 4],
            ['codigo' => '0402', 'descripcion' => 'CAMANA', 'departamento_id' => 4],
            ['codigo' => '0403', 'descripcion' => 'CARAVELI', 'departamento_id' => 4],
            ['codigo' => '0404', 'descripcion' => 'CASTILLA', 'departamento_id' => 4],
            ['codigo' => '0405', 'descripcion' => 'CAYLLOMA', 'departamento_id' => 4],
            ['codigo' => '0406', 'descripcion' => 'CONDESUYOS', 'departamento_id' => 4],
            ['codigo' => '0407', 'descripcion' => 'ISLAY', 'departamento_id' => 4],
            ['codigo' => '0408', 'descripcion' => 'LA UNION', 'departamento_id' => 4],
            ['codigo' => '0501', 'descripcion' => 'HUAMANGA', 'departamento_id' => 5],
            ['codigo' => '0502', 'descripcion' => 'CANGALLO', 'departamento_id' => 5],
            ['codigo' => '0503', 'descripcion' => 'HUANCA SANCOS', 'departamento_id' => 5],
            ['codigo' => '0504', 'descripcion' => 'HUANTA', 'departamento_id' => 5],
            ['codigo' => '0505', 'descripcion' => 'LA MAR', 'departamento_id' => 5],
            ['codigo' => '0506', 'descripcion' => 'LUCANAS', 'departamento_id' => 5],
            ['codigo' => '0507', 'descripcion' => 'PARINACOCHAS', 'departamento_id' => 5],
            ['codigo' => '0508', 'descripcion' => 'PAUCAR DEL SARA SARA', 'departamento_id' => 5],
            ['codigo' => '0509', 'descripcion' => 'SUCRE', 'departamento_id' => 5],
            ['codigo' => '0510', 'descripcion' => 'VICTOR FAJARDO', 'departamento_id' => 5],
            ['codigo' => '0511', 'descripcion' => 'VILCAS HUAMAN', 'departamento_id' => 5],
            ['codigo' => '0601', 'descripcion' => 'CAJAMARCA', 'departamento_id' => 6],
            ['codigo' => '0602', 'descripcion' => 'CAJABAMBA', 'departamento_id' => 6],
            ['codigo' => '0603', 'descripcion' => 'CELENDIN', 'departamento_id' => 6],
            ['codigo' => '0604', 'descripcion' => 'CHOTA', 'departamento_id' => 6],
            ['codigo' => '0605', 'descripcion' => 'CONTUMAZA', 'departamento_id' => 6],
            ['codigo' => '0606', 'descripcion' => 'CUTERVO', 'departamento_id' => 6],
            ['codigo' => '0607', 'descripcion' => 'HUALGAYOC', 'departamento_id' => 6],
            ['codigo' => '0608', 'descripcion' => 'JAEN', 'departamento_id' => 6],
            ['codigo' => '0609', 'descripcion' => 'SAN IGNACIO', 'departamento_id' => 6],
            ['codigo' => '0610', 'descripcion' => 'SAN MARCOS', 'departamento_id' => 6],
            ['codigo' => '0611', 'descripcion' => 'SAN MIGUEL', 'departamento_id' => 6],
            ['codigo' => '0612', 'descripcion' => 'SAN PABLO', 'departamento_id' => 6],
            ['codigo' => '0613', 'descripcion' => 'SANTA CRUZ', 'departamento_id' => 6],
            ['codigo' => '0701', 'descripcion' => 'PROV. CONST. DEL CALLAO', 'departamento_id' => 7],
            ['codigo' => '0801', 'descripcion' => 'CUSCO', 'departamento_id' => 8],
            ['codigo' => '0802', 'descripcion' => 'ACOMAYO', 'departamento_id' => 8],
            ['codigo' => '0803', 'descripcion' => 'ANTA', 'departamento_id' => 8],
            ['codigo' => '0804', 'descripcion' => 'CALCA', 'departamento_id' => 8],
            ['codigo' => '0805', 'descripcion' => 'CANAS', 'departamento_id' => 8],
            ['codigo' => '0806', 'descripcion' => 'CANCHIS', 'departamento_id' => 8],
            ['codigo' => '0807', 'descripcion' => 'CHUMBIVILCAS', 'departamento_id' => 8],
            ['codigo' => '0808', 'descripcion' => 'ESPINAR', 'departamento_id' => 8],
            ['codigo' => '0809', 'descripcion' => 'LA CONVENCION', 'departamento_id' => 8],
            ['codigo' => '0810', 'descripcion' => 'PARURO', 'departamento_id' => 8],
            ['codigo' => '0811', 'descripcion' => 'PAUCARTAMBO', 'departamento_id' => 8],
            ['codigo' => '0812', 'descripcion' => 'QUISPICANCHI', 'departamento_id' => 8],
            ['codigo' => '0813', 'descripcion' => 'URUBAMBA', 'departamento_id' => 8],
            ['codigo' => '0901', 'descripcion' => 'HUANCAVELICA', 'departamento_id' => 9],
            ['codigo' => '0902', 'descripcion' => 'ACOBAMBA', 'departamento_id' => 9],
            ['codigo' => '0903', 'descripcion' => 'ANGARAES', 'departamento_id' => 9],
            ['codigo' => '0904', 'descripcion' => 'CASTROVIRREYNA', 'departamento_id' => 9],
            ['codigo' => '0905', 'descripcion' => 'CHURCAMPA', 'departamento_id' => 9],
            ['codigo' => '0906', 'descripcion' => 'HUAYTARA', 'departamento_id' => 9],
            ['codigo' => '0907', 'descripcion' => 'TAYACAJA', 'departamento_id' => 9],
            ['codigo' => '1001', 'descripcion' => 'HUANUCO', 'departamento_id' => 10],
            ['codigo' => '1002', 'descripcion' => 'AMBO', 'departamento_id' => 10],
            ['codigo' => '1003', 'descripcion' => 'DOS DE MAYO', 'departamento_id' => 10],
            ['codigo' => '1004', 'descripcion' => 'HUACAYBAMBA', 'departamento_id' => 10],
            ['codigo' => '1005', 'descripcion' => 'HUAMALIES', 'departamento_id' => 10],
            ['codigo' => '1006', 'descripcion' => 'LEONCIO PRADO', 'departamento_id' => 10],
            ['codigo' => '1007', 'descripcion' => 'MARAÑON', 'departamento_id' => 10],
            ['codigo' => '1008', 'descripcion' => 'PACHITEA', 'departamento_id' => 10],
            ['codigo' => '1009', 'descripcion' => 'PUERTO INCA', 'departamento_id' => 10],
            ['codigo' => '1010', 'descripcion' => 'LAURICOCHA', 'departamento_id' => 10],
            ['codigo' => '1011', 'descripcion' => 'YAROWILCA', 'departamento_id' => 10],
            ['codigo' => '1101', 'descripcion' => 'ICA', 'departamento_id' => 11],
            ['codigo' => '1102', 'descripcion' => 'CHINCHA', 'departamento_id' => 11],
            ['codigo' => '1103', 'descripcion' => 'NAZCA', 'departamento_id' => 11],
            ['codigo' => '1104', 'descripcion' => 'PALPA', 'departamento_id' => 11],
            ['codigo' => '1105', 'descripcion' => 'PISCO', 'departamento_id' => 11],
            ['codigo' => '1201', 'descripcion' => 'HUANCAYO', 'departamento_id' => 12],
            ['codigo' => '1202', 'descripcion' => 'CONCEPCION', 'departamento_id' => 12],
            ['codigo' => '1203', 'descripcion' => 'CHANCHAMAYO', 'departamento_id' => 12],
            ['codigo' => '1204', 'descripcion' => 'JAUJA', 'departamento_id' => 12],
            ['codigo' => '1205', 'descripcion' => 'JUNIN', 'departamento_id' => 12],
            ['codigo' => '1206', 'descripcion' => 'SATIPO', 'departamento_id' => 12],
            ['codigo' => '1207', 'descripcion' => 'TARMA', 'departamento_id' => 12],
            ['codigo' => '1208', 'descripcion' => 'YAULI', 'departamento_id' => 12],
            ['codigo' => '1209', 'descripcion' => 'CHUPACA', 'departamento_id' => 12],
            ['codigo' => '1301', 'descripcion' => 'TRUJILLO', 'departamento_id' => 13],
            ['codigo' => '1302', 'descripcion' => 'ASCOPE', 'departamento_id' => 13],
            ['codigo' => '1303', 'descripcion' => 'BOLIVAR', 'departamento_id' => 13],
            ['codigo' => '1304', 'descripcion' => 'CHEPEN', 'departamento_id' => 13],
            ['codigo' => '1305', 'descripcion' => 'JULCAN', 'departamento_id' => 13],
            ['codigo' => '1306', 'descripcion' => 'OTUZCO', 'departamento_id' => 13],
            ['codigo' => '1307', 'descripcion' => 'PACASMAYO', 'departamento_id' => 13],
            ['codigo' => '1308', 'descripcion' => 'PATAZ', 'departamento_id' => 13],
            ['codigo' => '1309', 'descripcion' => 'SANCHEZ CARRION', 'departamento_id' => 13],
            ['codigo' => '1310', 'descripcion' => 'SANTIAGO DE CHUCO', 'departamento_id' => 13],
            ['codigo' => '1311', 'descripcion' => 'GRAN CHIMU', 'departamento_id' => 13],
            ['codigo' => '1312', 'descripcion' => 'VIRU', 'departamento_id' => 13],
            ['codigo' => '1401', 'descripcion' => 'CHICLAYO', 'departamento_id' => 14],
            ['codigo' => '1402', 'descripcion' => 'FERREÑAFE', 'departamento_id' => 14],
            ['codigo' => '1403', 'descripcion' => 'LAMBAYEQUE', 'departamento_id' => 14],
            ['codigo' => '1501', 'descripcion' => 'LIMA', 'departamento_id' => 15],
            ['codigo' => '1502', 'descripcion' => 'BARRANCA', 'departamento_id' => 15],
            ['codigo' => '1503', 'descripcion' => 'CAJATAMBO', 'departamento_id' => 15],
            ['codigo' => '1504', 'descripcion' => 'CANTA', 'departamento_id' => 15],
            ['codigo' => '1505', 'descripcion' => 'CAÑETE', 'departamento_id' => 15],
            ['codigo' => '1506', 'descripcion' => 'HUARAL', 'departamento_id' => 15],
            ['codigo' => '1507', 'descripcion' => 'HUAROCHIRI', 'departamento_id' => 15],
            ['codigo' => '1508', 'descripcion' => 'HUAURA', 'departamento_id' => 15],
            ['codigo' => '1509', 'descripcion' => 'OYON', 'departamento_id' => 15],
            ['codigo' => '1510', 'descripcion' => 'YAUYOS', 'departamento_id' => 15],
            ['codigo' => '1601', 'descripcion' => 'MAYNAS', 'departamento_id' => 16],
            ['codigo' => '1602', 'descripcion' => 'ALTO AMAZONAS', 'departamento_id' => 16],
            ['codigo' => '1603', 'descripcion' => 'LORETO', 'departamento_id' => 16],
            ['codigo' => '1604', 'descripcion' => 'MARISCAL RAMON CASTILLA', 'departamento_id' => 16],
            ['codigo' => '1605', 'descripcion' => 'REQUENA', 'departamento_id' => 16],
            ['codigo' => '1606', 'descripcion' => 'UCAYALI', 'departamento_id' => 16],
            ['codigo' => '1607', 'descripcion' => 'DATEM DEL MARAÑON', 'departamento_id' => 16],
            ['codigo' => '1701', 'descripcion' => 'TAMBOPATA', 'departamento_id' => 17],
            ['codigo' => '1702', 'descripcion' => 'MANU', 'departamento_id' => 17],
            ['codigo' => '1703', 'descripcion' => 'TAHUAMANU', 'departamento_id' => 17],
            ['codigo' => '1801', 'descripcion' => 'MARISCAL NIETO', 'departamento_id' => 18],
            ['codigo' => '1802', 'descripcion' => 'GENERAL SANCHEZ CERRO', 'departamento_id' => 18],
            ['codigo' => '1803', 'descripcion' => 'ILO', 'departamento_id' => 18],
            ['codigo' => '1901', 'descripcion' => 'PASCO', 'departamento_id' => 19],
            ['codigo' => '1902', 'descripcion' => 'DANIEL ALCIDES CARRION', 'departamento_id' => 19],
            ['codigo' => '1903', 'descripcion' => 'OXAPAMPA', 'departamento_id' => 19],
            ['codigo' => '2001', 'descripcion' => 'PIURA', 'departamento_id' => 20],
            ['codigo' => '2002', 'descripcion' => 'AYABACA', 'departamento_id' => 20],
            ['codigo' => '2003', 'descripcion' => 'HUANCABAMBA', 'departamento_id' => 20],
            ['codigo' => '2004', 'descripcion' => 'MORROPON', 'departamento_id' => 20],
            ['codigo' => '2005', 'descripcion' => 'PAITA', 'departamento_id' => 20],
            ['codigo' => '2006', 'descripcion' => 'SULLANA', 'departamento_id' => 20],
            ['codigo' => '2007', 'descripcion' => 'TALARA', 'departamento_id' => 20],
            ['codigo' => '2008', 'descripcion' => 'SECHURA', 'departamento_id' => 20],
            ['codigo' => '2101', 'descripcion' => 'PUNO', 'departamento_id' => 21],
            ['codigo' => '2102', 'descripcion' => 'AZANGARO', 'departamento_id' => 21],
            ['codigo' => '2103', 'descripcion' => 'CARABAYA', 'departamento_id' => 21],
            ['codigo' => '2104', 'descripcion' => 'CHUCUITO', 'departamento_id' => 21],
            ['codigo' => '2105', 'descripcion' => 'EL COLLAO', 'departamento_id' => 21],
            ['codigo' => '2106', 'descripcion' => 'HUANCANE', 'departamento_id' => 21],
            ['codigo' => '2107', 'descripcion' => 'LAMPA', 'departamento_id' => 21],
            ['codigo' => '2108', 'descripcion' => 'MELGAR', 'departamento_id' => 21],
            ['codigo' => '2109', 'descripcion' => 'MOHO', 'departamento_id' => 21],
            ['codigo' => '2110', 'descripcion' => 'SAN ANTONIO DE PUTINA', 'departamento_id' => 21],
            ['codigo' => '2111', 'descripcion' => 'SAN ROMAN', 'departamento_id' => 21],
            ['codigo' => '2112', 'descripcion' => 'SANDIA', 'departamento_id' => 21],
            ['codigo' => '2113', 'descripcion' => 'YUNGUYO', 'departamento_id' => 21],
            ['codigo' => '2201', 'descripcion' => 'MOYOBAMBA', 'departamento_id' => 22],
            ['codigo' => '2202', 'descripcion' => 'BELLAVISTA', 'departamento_id' => 22],
            ['codigo' => '2203', 'descripcion' => 'EL DORADO', 'departamento_id' => 22],
            ['codigo' => '2204', 'descripcion' => 'HUALLAGA', 'departamento_id' => 22],
            ['codigo' => '2205', 'descripcion' => 'LAMAS', 'departamento_id' => 22],
            ['codigo' => '2206', 'descripcion' => 'MARISCAL CACERES', 'departamento_id' => 22],
            ['codigo' => '2207', 'descripcion' => 'PICOTA', 'departamento_id' => 22],
            ['codigo' => '2208', 'descripcion' => 'RIOJA', 'departamento_id' => 22],
            ['codigo' => '2209', 'descripcion' => 'SAN MARTIN', 'departamento_id' => 22],
            ['codigo' => '2210', 'descripcion' => 'TOCACHE', 'departamento_id' => 22],
            ['codigo' => '2301', 'descripcion' => 'TACNA', 'departamento_id' => 23],
            ['codigo' => '2302', 'descripcion' => 'CANDARAVE', 'departamento_id' => 23],
            ['codigo' => '2303', 'descripcion' => 'JORGE BASADRE', 'departamento_id' => 23],
            ['codigo' => '2304', 'descripcion' => 'TARATA', 'departamento_id' => 23],
            ['codigo' => '2401', 'descripcion' => 'TUMBES', 'departamento_id' => 24],
            ['codigo' => '2402', 'descripcion' => 'CONTRALMIRANTE VILLAR', 'departamento_id' => 24],
            ['codigo' => '2403', 'descripcion' => 'ZARUMILLA', 'departamento_id' => 24],
            ['codigo' => '2501', 'descripcion' => 'CORONEL PORTILLO', 'departamento_id' => 25],
            ['codigo' => '2502', 'descripcion' => 'ATALAYA', 'departamento_id' => 25],
            ['codigo' => '2503', 'descripcion' => 'PADRE ABAD', 'departamento_id' => 25],
            ['codigo' => '2504', 'descripcion' => 'PURUS', 'departamento_id' => 25],

        ];

        DB::table('provincias')->insert($data);
    }
}
